name: Build and push slom container image

description: |
  Build and push slom container image.

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to the container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: docker/metadata-action@v5
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/ajalab/slom
    - name: Build and push container image
      uses: docker/build-push-action@v6
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args:
          MODULE_VERSION=${{ github.ref_name }}
