name: Build Go project

description: |
  Build Go project.

outputs:
  target:
    description: name of the built file
    value: ${{ steps.build.outputs.target }}

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: false
    - name: Restore cache
      uses: actions/cache/restore@v4
      id: go-cache
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: go-${{ hashFiles('go.sum') }}
        restore-keys: |
          go-
    - name: Build
      id: build
      run: |
        go build

        if [[ "$(go env GOOS)" = windows ]]; then
          target="$(basename $(pwd)).exe"
        else
          target="$(basename $(pwd))"
        fi

        echo target="$target" >> "$GITHUB_OUTPUT"
        echo "::debug::GOOS=$(go env GOOS), target=$target"
      shell: bash
    - name: Save cache
      uses: actions/cache/save@v4
      if: github.ref_name == 'main' && steps.go-cache.outputs.cache-hit != 'true'
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ steps.go-cache.outputs.cache-primary-key }}
