name: Release

on:
  release:
    types:
      - published

jobs:
  build-release-assets:
    strategy:
      matrix:
        os:
          - linux
          - darwin
          - windows
        arch:
          - amd64
          - arm64
        exclude:
          - os: windows
            arch: arm64
        include:
          - os: linux
            format: tar.gz
          - os: darwin
            format: tar.gz
          - os: windows
            format: zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Go
        id: build
        uses: ./.github/actions/build-go/
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
      - name: Upload release asset as artifact
        uses: ./.github/actions/upload-artifact-release-asset
        with:
          path: >
            ${{ steps.build.outputs.target }}
            LICENSE
          name: slom-${{ github.ref_name }}.${{ matrix.os }}-${{ matrix.arch }}
          format: ${{ matrix.format }}

  upload-release-assets:
    needs: build-release-assets
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download assets
        uses: actions/download-artifact@v4
        with:
          path: assets
          merge-multiple: true
      - name: Upload the assets to the release
        run: gh release upload -R "$GITHUB_REPOSITORY" "$GITHUB_REF_NAME" assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
